server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    lease-expiration-duration-in-seconds: 25
  server:
    enableSelfPreservation: false
    expected-client-renewal-interval-seconds: 15
    renewal-percent-threshold: 0.85
spring:
  application:
    name: service-discovery-server
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
