
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
spring:
  application:
    name: service-discovery-server
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
