server:
  port: ${PORT}
#  port: ${random.int(20002,29999)}
spring:
  application:
    name: microservizio-2
eureka:
  client:
    should-unregister-on-shutdown: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    lease-renewal-interval-in-seconds: 30
    preferIpAddress: true
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    metadataMap:
#      grpc.port: 6565

